"""Shim: prompts live in ``features.generation.prompts`` (stable import path ``prompts``)."""

from features.generation.prompts import (
    build_checker_user,
    build_generation_user_message,
    build_structured_generation_user_message,
    checker_system,
    densify_system,
    fixer_compile_system,
    fixer_system,
    generator_system,
    revision_user_densify,
    revision_user_densify_structured,
    revision_user_fix_ats,
    revision_user_fix_ats_structured,
    revision_user_fix_compile,
    revision_user_fix_compile_structured,
    revision_user_fix_schema,
    revision_user_one_page,
    revision_user_fit_one_page_structured,
    structured_densify_system,
    structured_fixer_compile_system,
    structured_fixer_system,
    structured_generator_system,
)

__all__ = [
    "build_checker_user",
    "build_generation_user_message",
    "build_structured_generation_user_message",
    "checker_system",
    "densify_system",
    "fixer_compile_system",
    "fixer_system",
    "generator_system",
    "revision_user_densify",
    "revision_user_densify_structured",
    "revision_user_fix_ats",
    "revision_user_fix_ats_structured",
    "revision_user_fix_compile",
    "revision_user_fix_compile_structured",
    "revision_user_fix_schema",
    "revision_user_one_page",
    "revision_user_fit_one_page_structured",
    "structured_densify_system",
    "structured_fixer_compile_system",
    "structured_fixer_system",
    "structured_generator_system",
]
